if [[ "$ZPROF" = true ]]; then
  zmodload zsh/zprof
fi

export PATH=/opt/homebrew/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

DOTS=$HOME/dotfiles

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="myagnoster"
# ZSH_THEME="powerline-go"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

DEFAULT_USER=$(whoami)

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$DOTS/oh-my-zsh

# use ripgrep with fzf
export FZF_BASE='/opt/homebrew/opt/fzf'
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'

function zvm_after_init() {
  # Set up fzf key bindings and fuzzy completion
  source <(fzf --zsh)
  bindkey 'ç' fzf-cd-widget
  bindkey '\eOA' up-line-or-beginning-search
  bindkey '\e[A' up-line-or-beginning-search
  bindkey '\eOB' down-line-or-beginning-search
  bindkey '\e[B' down-line-or-beginning-search
  export ZVM_VI_EDITOR=nvim
}

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(brew extract tmux)
plugins+=(zsh-vi-mode)

typeset -gU fpath path

fpath=(
	# /usr/local/share/zsh/site-functions
	$fpath
)

# fpath=($HOME/sandbox/docker/zsh-completions $fpath)
source $ZSH/oh-my-zsh.sh
# autoload -U compinit && compinit

# ulimit
ulimit -n 524288
ulimit -u 2048

# History settings
#
HISTSIZE=100000
SAVEHIST=100000
# setopt APPEND_HISTORY          # append rather than overwrite history file.
setopt HIST_EXPIRE_DUPS_FIRST    # allow dups, but expire old ones when I hit HISTSIZE
setopt extendedglob
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.

############################################## User configuration
autoload -U zmv
# autoload -Uz up-line-or-beginning-search
# autoload -Uz down-line-or-beginning-search
# zle -N up-line-or-beginning-search
# zle -N down-line-or-beginning-search
# bindkey '\eOA' up-line-or-beginning-search
# bindkey '\e[A' up-line-or-beginning-search
# bindkey '\eOB' down-line-or-beginning-search
# bindkey '\e[B' down-line-or-beginning-search
# option-c for fzf cd

# export PAGER="less"

# Less options
# -F or --quit-if-one-screen
# -R or --RAW-CONTROL-CHARS (needed for colorizing output)
# -s or --squeeze-blank-lines
# -X or --no-init (don't clear the screen when less exits)
# LESS="-FRX"; export LESS
# LESSOPEN="|lesspipe.sh %s"; export LESSOPEN
# export LS_COLORS='di=01;34:ln=36:so=32:pi=33:ex=32:bd=34;46:cd=34;43:su=0;41:sg=30;46:tw=30;42:ow=37;45'

# Vagrant
# export VAGRANT_DEFAULT_PROVIDER='vmware_fusion'
export VAGRANT_DEFAULT_PROVIDER='virtualbox'

# Editor and Pager
EDITOR="vim"
export EDITOR
export LESS='-R'
export LESSOPEN='|~/.lessfilter %s'
# export LESSOPEN="|/opt/homebrew/bin/lesspipe.sh %s"
PAGER="less -FirSwX"
MANPAGER="$PAGER"
export PAGER MANPAGER

source $DOTS/zsh/aliases
source $DOTS/zsh/functions
source $HOME/.creds/homebrew
[ -f $HOME/.creds/circleci ] && source $HOME/.creds/circleci
[ -f $HOME/.creds/artifactory ] && source $HOME/.creds/artifactory

export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin

############################ BEGIN PATH ############################

path=(
	$HOME/bin
	$HOME/.local/bin
	$HOME/.cargo/bin
	/usr/local/bin
  $GOBIN
	# /usr/local/opt/go/libexec/bin
	/usr/{bin,sbin}
	/{bin,sbin}
	/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support
)

eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(dircolors ~/.dircolors)"

# For compilers to find protobuf@3.6 you may need to set:
# export LDFLAGS="-L/usr/local/opt/protobuf@3.6/lib"
# export CPPFLAGS="-I/usr/local/opt/protobuf@3.6/include"

############################ END PATH ############################

eval "$(direnv hook zsh)"

autoload -U +X bashcompinit && bashcompinit

# Keep previous versions of homebrew formulas around
export HOMEBREW_NO_INSTALL_CLEANUP=1
# Don't update homebrew automatically
export HOMEBREW_NO_AUTO_UPDATE=1

# Use vim as a MANPAGER
# export MANPAGER="vim -c MANPAGER -"

[ -f $DOTS/zsh/privaterc ] && source $DOTS/zsh/privaterc

# complete -o nospace -C $HOME/sandbox/go/landing/bin/vault vault
complete -o nospace -C vault vault

eval "$(jira --completion-script-zsh)"
# vi mode
# source $DOTS/zsh/vim-mode-rc

# oh-my-zsh vi-mode plugin settings
# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/vi-mode
#
# VI_MODE_SET_CURSOR: controls whether the cursor style is changed when
# switching to a different input mode. Set it to true to enable it
# (default: unset):
# export VI_MODE_SET_CURSOR=true

# Configure help command for zsh
# https://superuser.com/a/1563859
unalias run-help
autoload run-help
export HELPDIR=$(command brew --prefix)/share/zsh/help
alias help=run-help

if [[ "$ZPROF" = true ]]; then
  zprof
fi

complete -o nospace -C boundary boundary
# zvm_after_init_commands+=("bindkey '^[[A' up-line-or-search" "bindkey '^[[B' down-line-or-search")
# vim: set filetype=zsh:

if [[ -d "$HOME/.lmstudio/bin" ]]; then
  export PATH="$PATH:$HOME/.lmstudio/bin"
fi
